# Generated by Django 5.1.1 on 2024-09-18 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='descripcion',
            new_name='descriptio',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='terminado',
            new_name='done',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='titulo',
            new_name='title',
        ),
    ]
