# Generated by Django 5.1.1 on 2024-09-18 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_descripcion_task_descriptio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='descriptio',
            new_name='description',
        ),
    ]
